### ISSUE TITLE
Tumor only mode

### ISSUE THREAD

**Issue by vincentye2** [roland-rad-lab/MoCaSeq#11]
Hi there,

I'm currently trying to use this pipeline to analyze a series of mouse brain tumors that were sent for WES. Unfortunately we did not collect matched normal samples. We do have a panel of controls. I'm hoping to do single-sample tumor analysis and was wondering if there is a way to use our panel of controls similar to the GATK option of creating a PanelOfNormals?

Thanks

**Comment by NikdAK** [comment]
Hi,
MoCaSeq itself does not accept a panel of normals for filtering, but you have several options.

Depending on the data format of your panel of normals you could simply provide a normal BAM/FASTQ for each tumor sample. 

Alternatively you could do a normal-only run to generate the unfiltered .m2.vcf files (or use existing VCFs) for GATK-CreateSomaticPanelOfNormals, followed by the tumor-only runs with a subsequent manual filtering using e.g. GATK-VariantFiltration.

For copynumber you could use CNVKit, which has the option to generate/use a panel of normals 
(--output-reference; https://cnvkit.readthedocs.io/en/stable/pipeline.html)

**Comment by vincentye2** [comment]
Thanks Niklas. 

I'm having an issue getting the pipeline to run as I get this error during the initialization: 

> Error occurred during initialization of VM
Could not reserve enough space for 367001600KB object heap
Error occurred during initialization of VM

I'm runnning this through my institution's HPC. Since users on the HPC don't have sudo access I'm using singularity to pull through the dockerized version of mocaseq. I've gradually increased mem and vmem on my batch job from 100GB to 350GB but still encounter the issue with object heap.

Here is the code I'm running:
`#!/bin/bash
#PBS -N 159LMoCaSeq

#PBS -l nodes=1:ppn=8
#PBS -l gres=localhd:100
#PBS -l mem=350g
#PBS -l vmem=350g
#PBS -l walltime=72:00:00
#PBS -joe /hpf/projects/dirkslab/People/Vincent/Exome_Aln

module load Singularity

working_directory=/hpf/projects/dirkslab/People/Vincent/mocaseq/workingdirectory
mkdir -p ${working_directory}
reference_directory=/hpf/projects/dirkslab/People/Vincent/mocaseq/ref
mkdir -p ${reference_directory}
temp_directory=/hpf/projects/dirkslab/People/Vincent/mocaseq/workingdirectory/temp
mkdir -p ${temp_directory}

cd /hpf/projects/dirkslab/People/Vincent/mocaseq

export SINGULARITY_BIND="${working_directory}:/var/pipeline/"
export SINGULARITY_BIND="${reference_directory}:/var/pipeline/ref/"
export SINGULARITY_BIND="${temp_directory}:/var/pipeline/temp"
singularity run mocaseq_latest.sif \
--bam_tumor '/var/pipeline/raw/159Lu.bam' \
--bam_normal '/var/pipeline/raw/DirksControlBrain1u.bam' \
--repeat_mapping yes \
--name 159L-WES \
--sequencing_type WES \
--threads 8 \
--RAM 350 \
--artefact GT`

I've attached the QC report and the output from my batch job submission.
[159Lo.txt](https://github.com/roland-rad-lab/MoCaSeq/files/8309881/159Lo.txt)

[159L-WES.report.txt](https://github.com/roland-rad-lab/MoCaSeq/files/8309882/159L-WES.report.txt)

Thanks

**Comment by sc13-bioinf** [comment]
Dear vincentye2,
Try reducing the amount given to the --RAM argument to MoCaSeq. (but keep the number given to your scheduler higher than this)
