### ISSUE TITLE
Manual installation and run

### ISSUE THREAD

**Issue by soumyarao86** [roland-rad-lab/MoCaSeq#12]
Hi,
I am using anaconda and can't use docker.
Is there a way to run the commands on Ubuntu?
I have got the code but am not sure if manual installation requires any additional steps or not. 
```
https://github.com/roland-rad-lab/MoCaSeq.git
```
Regards,
Soumya

**Comment by NikdAK** [comment]
Hi Soumya,

you would need to rebuild the entire environment in anaconda. 

All the commands are Ubuntu-based and you can finde them in the Dockerfile. 
Just remove the "RUN" infront of every installation command. 

You can also check the updated version found here: https://github.com/roland-rad-lab/MoCaSeq/blob/human-pipeline/Dockerfile

Good luck!

**Comment by soumyarao86** [comment]
Thanks you.
I will try to rebuild the environment in anaconda.
