### ISSUE TITLE
CNV

### ISSUE THREAD

**Issue by nilesh-iiita** [roland-rad-lab/MoCaSeq#13]
Unable to access copy number variation results.

**Comment by NikdAK** [comment]
Could you please provide us more information about the issue? Are the BAM files or other files created? 

There is a log file located here where you can extract more details about your issue: QC/samplename.report

**Comment by nilesh-iiita** [comment]
Thanks for the reply, I figured it out. The CNV data is in the Copywriter.genes.Mode.txt file. Though I did not how Mean values are calculated. Would you please briefly explain?

**Comment by NikdAK** [comment]
The value for each gene is taken as the average of all overlapping segments (should in most cases be just 1 segment). 

The copynumber value ("Mean" of all copy ratios) is calculated using Copywriter: 
https://pubmed.ncbi.nlm.nih.gov/25887352/
https://github.com/PeeperLab/CopywriteR
