### ISSUE TITLE
Docs for the `-rb` option

### ISSUE THREAD

**Issue by soymintc** [roland-rad-lab/MoCaSeq#14]
Hi,

I'm trying to run MoCaSeq using pre-aligned bams to GRCm38/mm10. Since I'm using paired bam files as input, I'd be using -nb and -tb options.
README says I have to specify the `-rb` option, however, I can't find any information about it. Could you please add some info about this option in README or its corresponding docs? 

Thank you 👍

**Comment by NikdAK** [comment]
Hi,
this might be a typo and actually should be -rm in the docs (--repeat_mapping, which is true by default anyways).
I think it should work if you just start it :)

**Comment by soymintc** [comment]
Hi @NikdAK thanks for the reply! No worries then. Will close the issue 👍
