### ISSUE TITLE
What allelic fraction is used as a cutoff in calling mutations? 

### ISSUE THREAD

**Issue by nilesh-iiita** [roland-rad-lab/MoCaSeq#16]
Hi, 

Where I can get the cutoff percent regarding allelic fraction to calling mutations? 

Best regards

**Comment by NikdAK** [comment]
Hi,
the following cutoffs are applied, depending on which filtering option you choose. The default is "hard" (but note that "all" is actually the less stringed filtering). 
GEN[Tumor].AF >= 0.1 means only mutations with 10% or more used.

if [ $filtering = 'all' ]; then
	cat $name/results/Mutect2/$name.m2.filt.selected.vcf \
	| java -jar $snpeff_dir/SnpSift.jar filter \
	"( ( FILTER = 'PASS') & (GEN[Tumor].AF >= 0.05) & \
	( ( GEN[Tumor].AD[0] + GEN[Tumor].AD[1]) >= 5 ) & \
	( ( GEN[Normal].AD[0] + GEN[Normal].AD[1]) >= 5 ) & \
	(GEN[Tumor].AD[1] >= 2) & (GEN[Normal].AD[1] <= 1) )" \
	> $name/results/Mutect2/$name.m2.postprocessed.vcf
elif [ $filtering = 'hard' ]; then
	cat $name/results/Mutect2/$name.m2.filt.selected.vcf \
	| java -jar $snpeff_dir/SnpSift.jar filter \
	"( ( FILTER = 'PASS') & (GEN[Tumor].AF >= 0.1) & \
	( ( GEN[Tumor].AD[0] + GEN[Tumor].AD[1]) >= 10 ) & \
	( ( GEN[Normal].AD[0] + GEN[Normal].AD[1]) >= 10 ) & \
	(GEN[Tumor].AD[1] >= 3) & (GEN[Normal].AD[1] = 0) )" \
	> $name/results/Mutect2/$name.m2.postprocessed.vcf
elif [ $filtering = 'none' ]; then
	cat $name/results/Mutect2/$name.m2.filt.selected.vcf \
	| java -jar $snpeff_dir/SnpSift.jar filter \
	"( ( FILTER = 'PASS' ) )" \
	> $name/results/Mutect2/$name.m2.postprocessed.vcf
fi

You can find the steps here: SNV_Mutect2Postprocessing.sh

**Comment by nilesh-iiita** [comment]
If I am correct you are referring to:
`echo "	-filt, --filtering       Set to 'all' (AF >= 0.05, , Variant in Tumor >= 2, Variant in Normal <= 1, Coverage >= 5), 'hard' (AF >= 0.1, Variant in Tumor >= 3, Variant in Normal = 0, Coverage >= 10) or 'none' (no filters). Optional. Defaults to 'hard'."`


Thanks

**Comment by NikdAK** [comment]
Yes
