### ISSUE TITLE
Mistake in CNV_CopywriterGetModeCorrectionFactor.R ?

### ISSUE THREAD

**Issue by DavideBrex** [roland-rad-lab/MoCaSeq#2]
Hi,
I was looking at the re-normalization step of your pipeline and I noticed a possible mistake in the script _CNV_CopywriterGetModeCorrectionFactor.R_ .
Here:
```
segmentData$seg.mean = segmentData$Mean-Shift
segmentData=segmentData[,c("Chrom", "Start", "End", "Mean")]
```

_segmentData_ contains the columns **Chrom, Start, End, Mean**. The column **seq.mean** is then added, but in line 26 the table is updated keeping the old **Mean** column, and not the one with the correction (_Mean - Shift_). I believe this is a mistake.

Thank you for your nice work.

Best regards

**Comment by NikdAK** [comment]
Thank you very much for this observation!
This is indeed a small mistake and will be fixed in the soon upcoming release.

Here is the solution, in case someone wants to run an analysis right now:
```
segmentData=segmentData[,c("Chrom", "Start", "End", "seg.mean")]
names(segmentData)[names(segmentData) == "seg.mean"] <- "Mean"
```
