### ISSUE TITLE
Mutation Post-Processing Script Issues

### ISSUE THREAD

**Issue by justinkhuang** [roland-rad-lab/MoCaSeq#3]
Hi,
I think there are a couple of small bugs in the PostProcessing scripts during the usage of VEP for mutation annotation.
1) In the [SNV_StrelkaPostprocessing.sh](https://github.com/roland-rad-lab/MoCaSeq/blob/master/repository/SNV_StrelkaPostprocessing.sh) script (line 104), the parameter for --cache_version is set to 95, but the cache version downloaded as the reference is version 96.
2) The PolyPhen flag is used for VEP annotation for all calls of VEP after mutation calling, but this is not a valid flag for VEP when annotating non-human variants, so an exception is thrown in the report log for each post-processing step and may throw further issues in the downstream commands in the post-processing scripts.

I noticed another issue when using the artefact flag (whether GT or CT) it is worth noting that the GATK version needs to be set to an earlier version than the default (e.g. to 4.1.4.1) otherwise the post-processing scripts run into issues trying to use the "FilterByOrientationBias" command

**Comment by NikdAK** [comment]
Hi,
thank you very much for this report. 

I am currently working on a major update, which fixes all these error messages and small problems. 
Further this update will allow MoCaSeq to be used for human data.

It hope to have it all finished in about 1-2 weeks, I will let you know.
